/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: subdata.proto */

#ifndef PROTOBUF_C_subdata_2eproto__INCLUDED
#define PROTOBUF_C_subdata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Subdata__SubPoint Subdata__SubPoint;
typedef struct _Subdata__SubPoints Subdata__SubPoints;


/* --- enums --- */


/* --- messages --- */

struct  _Subdata__SubPoint
{
  ProtobufCMessage base;
  char *assetid;
  char *pointid;
  protobuf_c_boolean has_time;
  int64_t time;
  char *value;
  protobuf_c_boolean has_quality;
  int32_t quality;
  protobuf_c_boolean has_edq;
  int32_t edq;
  char *datatype;
  char *subdatatype;
  protobuf_c_boolean has_oemtime;
  int64_t oemtime;
  char *attr;
  char *spanid;
  char *traceid;
  protobuf_c_boolean has_sendremote;
  protobuf_c_boolean sendremote;
};
#define SUBDATA__SUB_POINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&subdata__sub_point__descriptor) \
    , NULL, NULL, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 0 }


struct  _Subdata__SubPoints
{
  ProtobufCMessage base;
  size_t n_points;
  Subdata__SubPoint **points;
};
#define SUBDATA__SUB_POINTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&subdata__sub_points__descriptor) \
    , 0,NULL }


/* Subdata__SubPoint methods */
void   subdata__sub_point__init
                     (Subdata__SubPoint         *message);
size_t subdata__sub_point__get_packed_size
                     (const Subdata__SubPoint   *message);
size_t subdata__sub_point__pack
                     (const Subdata__SubPoint   *message,
                      uint8_t             *out);
size_t subdata__sub_point__pack_to_buffer
                     (const Subdata__SubPoint   *message,
                      ProtobufCBuffer     *buffer);
Subdata__SubPoint *
       subdata__sub_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   subdata__sub_point__free_unpacked
                     (Subdata__SubPoint *message,
                      ProtobufCAllocator *allocator);
/* Subdata__SubPoints methods */
void   subdata__sub_points__init
                     (Subdata__SubPoints         *message);
size_t subdata__sub_points__get_packed_size
                     (const Subdata__SubPoints   *message);
size_t subdata__sub_points__pack
                     (const Subdata__SubPoints   *message,
                      uint8_t             *out);
size_t subdata__sub_points__pack_to_buffer
                     (const Subdata__SubPoints   *message,
                      ProtobufCBuffer     *buffer);
Subdata__SubPoints *
       subdata__sub_points__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   subdata__sub_points__free_unpacked
                     (Subdata__SubPoints *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Subdata__SubPoint_Closure)
                 (const Subdata__SubPoint *message,
                  void *closure_data);
typedef void (*Subdata__SubPoints_Closure)
                 (const Subdata__SubPoints *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor subdata__sub_point__descriptor;
extern const ProtobufCMessageDescriptor subdata__sub_points__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_subdata_2eproto__INCLUDED */
