/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: controlresponsepoint.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "controlresponsepoint.pb-c.h"
void   controlresponsedata__control_response_point__init
                     (Controlresponsedata__ControlResponsePoint         *message)
{
  static const Controlresponsedata__ControlResponsePoint init_value = CONTROLRESPONSEDATA__CONTROL_RESPONSE_POINT__INIT;
  *message = init_value;
}
size_t controlresponsedata__control_response_point__get_packed_size
                     (const Controlresponsedata__ControlResponsePoint *message)
{
  assert(message->base.descriptor == &controlresponsedata__control_response_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t controlresponsedata__control_response_point__pack
                     (const Controlresponsedata__ControlResponsePoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &controlresponsedata__control_response_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t controlresponsedata__control_response_point__pack_to_buffer
                     (const Controlresponsedata__ControlResponsePoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &controlresponsedata__control_response_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Controlresponsedata__ControlResponsePoint *
       controlresponsedata__control_response_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Controlresponsedata__ControlResponsePoint *)
     protobuf_c_message_unpack (&controlresponsedata__control_response_point__descriptor,
                                allocator, len, data);
}
void   controlresponsedata__control_response_point__free_unpacked
                     (Controlresponsedata__ControlResponsePoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &controlresponsedata__control_response_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   controlresponsedata__control_response_points__init
                     (Controlresponsedata__ControlResponsePoints         *message)
{
  static const Controlresponsedata__ControlResponsePoints init_value = CONTROLRESPONSEDATA__CONTROL_RESPONSE_POINTS__INIT;
  *message = init_value;
}
size_t controlresponsedata__control_response_points__get_packed_size
                     (const Controlresponsedata__ControlResponsePoints *message)
{
  assert(message->base.descriptor == &controlresponsedata__control_response_points__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t controlresponsedata__control_response_points__pack
                     (const Controlresponsedata__ControlResponsePoints *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &controlresponsedata__control_response_points__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t controlresponsedata__control_response_points__pack_to_buffer
                     (const Controlresponsedata__ControlResponsePoints *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &controlresponsedata__control_response_points__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Controlresponsedata__ControlResponsePoints *
       controlresponsedata__control_response_points__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Controlresponsedata__ControlResponsePoints *)
     protobuf_c_message_unpack (&controlresponsedata__control_response_points__descriptor,
                                allocator, len, data);
}
void   controlresponsedata__control_response_points__free_unpacked
                     (Controlresponsedata__ControlResponsePoints *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &controlresponsedata__control_response_points__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor controlresponsedata__control_response_point__field_descriptors[21] =
{
  {
    "requestId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, requestid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, messageid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestMethod",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, requestmethod),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "callType",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, calltype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "controlChannelId",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, controlchannelid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "productKey",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, productkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceKey",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, devicekey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assetId",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, assetid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serviceName",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, servicename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serviceId",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, serviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "callbackUrl",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, callbackurl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputData",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, inputdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputData",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, outputdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "submsg",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, submsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gmtServiceRequest",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, gmtservicerequest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gmtServiceReply",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, gmtservicereply),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gmtDeviceReply",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, gmtdevicereply),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Controlresponsedata__ControlResponsePoint, attr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned controlresponsedata__control_response_point__field_indices_by_name[] = {
  7,   /* field[7] = assetId */
  20,   /* field[20] = attr */
  3,   /* field[3] = callType */
  10,   /* field[10] = callbackUrl */
  4,   /* field[4] = controlChannelId */
  6,   /* field[6] = deviceKey */
  19,   /* field[19] = gmtDeviceReply */
  18,   /* field[18] = gmtServiceReply */
  17,   /* field[17] = gmtServiceRequest */
  11,   /* field[11] = inputData */
  1,   /* field[1] = messageId */
  14,   /* field[14] = msg */
  12,   /* field[12] = outputData */
  5,   /* field[5] = productKey */
  0,   /* field[0] = requestId */
  2,   /* field[2] = requestMethod */
  9,   /* field[9] = serviceId */
  8,   /* field[8] = serviceName */
  13,   /* field[13] = status */
  15,   /* field[15] = submsg */
  16,   /* field[16] = timeout */
};
static const ProtobufCIntRange controlresponsedata__control_response_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor controlresponsedata__control_response_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "controlresponsedata.ControlResponsePoint",
  "ControlResponsePoint",
  "Controlresponsedata__ControlResponsePoint",
  "controlresponsedata",
  sizeof(Controlresponsedata__ControlResponsePoint),
  21,
  controlresponsedata__control_response_point__field_descriptors,
  controlresponsedata__control_response_point__field_indices_by_name,
  1,  controlresponsedata__control_response_point__number_ranges,
  (ProtobufCMessageInit) controlresponsedata__control_response_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor controlresponsedata__control_response_points__field_descriptors[1] =
{
  {
    "points",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Controlresponsedata__ControlResponsePoints, n_points),
    offsetof(Controlresponsedata__ControlResponsePoints, points),
    &controlresponsedata__control_response_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned controlresponsedata__control_response_points__field_indices_by_name[] = {
  0,   /* field[0] = points */
};
static const ProtobufCIntRange controlresponsedata__control_response_points__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor controlresponsedata__control_response_points__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "controlresponsedata.ControlResponsePoints",
  "ControlResponsePoints",
  "Controlresponsedata__ControlResponsePoints",
  "controlresponsedata",
  sizeof(Controlresponsedata__ControlResponsePoints),
  1,
  controlresponsedata__control_response_points__field_descriptors,
  controlresponsedata__control_response_points__field_indices_by_name,
  1,  controlresponsedata__control_response_points__number_ranges,
  (ProtobufCMessageInit) controlresponsedata__control_response_points__init,
  NULL,NULL,NULL    /* reserved[123] */
};
