/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssrecordpoint.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ssrecordpoint.pb-c.h"
void   ssrecorddata__ssrecord_point__init
                     (Ssrecorddata__SSRecordPoint         *message)
{
  static const Ssrecorddata__SSRecordPoint init_value = SSRECORDDATA__SSRECORD_POINT__INIT;
  *message = init_value;
}
size_t ssrecorddata__ssrecord_point__get_packed_size
                     (const Ssrecorddata__SSRecordPoint *message)
{
  assert(message->base.descriptor == &ssrecorddata__ssrecord_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssrecorddata__ssrecord_point__pack
                     (const Ssrecorddata__SSRecordPoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssrecorddata__ssrecord_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssrecorddata__ssrecord_point__pack_to_buffer
                     (const Ssrecorddata__SSRecordPoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssrecorddata__ssrecord_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ssrecorddata__SSRecordPoint *
       ssrecorddata__ssrecord_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ssrecorddata__SSRecordPoint *)
     protobuf_c_message_unpack (&ssrecorddata__ssrecord_point__descriptor,
                                allocator, len, data);
}
void   ssrecorddata__ssrecord_point__free_unpacked
                     (Ssrecorddata__SSRecordPoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssrecorddata__ssrecord_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssrecorddata__ssrecord_points__init
                     (Ssrecorddata__SSRecordPoints         *message)
{
  static const Ssrecorddata__SSRecordPoints init_value = SSRECORDDATA__SSRECORD_POINTS__INIT;
  *message = init_value;
}
size_t ssrecorddata__ssrecord_points__get_packed_size
                     (const Ssrecorddata__SSRecordPoints *message)
{
  assert(message->base.descriptor == &ssrecorddata__ssrecord_points__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssrecorddata__ssrecord_points__pack
                     (const Ssrecorddata__SSRecordPoints *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssrecorddata__ssrecord_points__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssrecorddata__ssrecord_points__pack_to_buffer
                     (const Ssrecorddata__SSRecordPoints *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssrecorddata__ssrecord_points__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ssrecorddata__SSRecordPoints *
       ssrecorddata__ssrecord_points__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ssrecorddata__SSRecordPoints *)
     protobuf_c_message_unpack (&ssrecorddata__ssrecord_points__descriptor,
                                allocator, len, data);
}
void   ssrecorddata__ssrecord_points__free_unpacked
                     (Ssrecorddata__SSRecordPoints *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssrecorddata__ssrecord_points__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssrecorddata__ssrecord_point__field_descriptors[19] =
{
  {
    "orgId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, orgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modelId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, modelid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assetId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, assetid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collectDeviceId",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, collectdeviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pointId",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, pointid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dq",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, dq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modelPath",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, modelpath),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "policyType",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, policytype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signalType",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, signaltype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hasQuality",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, hasquality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataType",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, datatype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subDataType",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, subdatatype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ssrecorddata__SSRecordPoint, attr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usingOem",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ssrecorddata__SSRecordPoint, has_usingoem),
    offsetof(Ssrecorddata__SSRecordPoint, usingoem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oemTime",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Ssrecorddata__SSRecordPoint, has_oemtime),
    offsetof(Ssrecorddata__SSRecordPoint, oemtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pointType",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ssrecorddata__SSRecordPoint, has_pointtype),
    offsetof(Ssrecorddata__SSRecordPoint, pointtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssrecorddata__ssrecord_point__field_indices_by_name[] = {
  2,   /* field[2] = assetId */
  15,   /* field[15] = attr */
  3,   /* field[3] = collectDeviceId */
  13,   /* field[13] = dataType */
  8,   /* field[8] = dq */
  12,   /* field[12] = hasQuality */
  1,   /* field[1] = modelId */
  9,   /* field[9] = modelPath */
  17,   /* field[17] = oemTime */
  0,   /* field[0] = orgId */
  4,   /* field[4] = pointId */
  18,   /* field[18] = pointType */
  10,   /* field[10] = policyType */
  7,   /* field[7] = quality */
  11,   /* field[11] = signalType */
  14,   /* field[14] = subDataType */
  5,   /* field[5] = time */
  16,   /* field[16] = usingOem */
  6,   /* field[6] = value */
};
static const ProtobufCIntRange ssrecorddata__ssrecord_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor ssrecorddata__ssrecord_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ssrecorddata.SSRecordPoint",
  "SSRecordPoint",
  "Ssrecorddata__SSRecordPoint",
  "ssrecorddata",
  sizeof(Ssrecorddata__SSRecordPoint),
  19,
  ssrecorddata__ssrecord_point__field_descriptors,
  ssrecorddata__ssrecord_point__field_indices_by_name,
  1,  ssrecorddata__ssrecord_point__number_ranges,
  (ProtobufCMessageInit) ssrecorddata__ssrecord_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssrecorddata__ssrecord_points__field_descriptors[1] =
{
  {
    "points",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ssrecorddata__SSRecordPoints, n_points),
    offsetof(Ssrecorddata__SSRecordPoints, points),
    &ssrecorddata__ssrecord_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssrecorddata__ssrecord_points__field_indices_by_name[] = {
  0,   /* field[0] = points */
};
static const ProtobufCIntRange ssrecorddata__ssrecord_points__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ssrecorddata__ssrecord_points__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ssrecorddata.SSRecordPoints",
  "SSRecordPoints",
  "Ssrecorddata__SSRecordPoints",
  "ssrecorddata",
  sizeof(Ssrecorddata__SSRecordPoints),
  1,
  ssrecorddata__ssrecord_points__field_descriptors,
  ssrecorddata__ssrecord_points__field_indices_by_name,
  1,  ssrecorddata__ssrecord_points__number_ranges,
  (ProtobufCMessageInit) ssrecorddata__ssrecord_points__init,
  NULL,NULL,NULL    /* reserved[123] */
};
