/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: setmeasurepointresponsepoint.proto */

#ifndef PROTOBUF_C_setmeasurepointresponsepoint_2eproto__INCLUDED
#define PROTOBUF_C_setmeasurepointresponsepoint_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Setmeasurepointresponsedata__SetMeasurepointResponsePoint Setmeasurepointresponsedata__SetMeasurepointResponsePoint;
typedef struct _Setmeasurepointresponsedata__SetMeasurepointResponsePoints Setmeasurepointresponsedata__SetMeasurepointResponsePoints;


/* --- enums --- */


/* --- messages --- */

struct  _Setmeasurepointresponsedata__SetMeasurepointResponsePoint
{
  ProtobufCMessage base;
  char *requestid;
  char *orgid;
  char *calltype;
  char *setmeasurepointchannelid;
  char *productkey;
  char *devicekey;
  char *assetid;
  char *measurepointid;
  char *callbackurl;
  char *inputdata;
  int64_t status;
  char *msg;
  char *submsg;
  int64_t timeout;
  int64_t gmtsetmeasurepointrequest;
  int64_t gmtsetmeasurepointreply;
  char *attr;
};
#define SETMEASUREPOINTRESPONSEDATA__SET_MEASUREPOINT_RESPONSE_POINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&setmeasurepointresponsedata__set_measurepoint_response_point__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 0, 0, 0, NULL }


struct  _Setmeasurepointresponsedata__SetMeasurepointResponsePoints
{
  ProtobufCMessage base;
  size_t n_points;
  Setmeasurepointresponsedata__SetMeasurepointResponsePoint **points;
};
#define SETMEASUREPOINTRESPONSEDATA__SET_MEASUREPOINT_RESPONSE_POINTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&setmeasurepointresponsedata__set_measurepoint_response_points__descriptor) \
    , 0,NULL }


/* Setmeasurepointresponsedata__SetMeasurepointResponsePoint methods */
void   setmeasurepointresponsedata__set_measurepoint_response_point__init
                     (Setmeasurepointresponsedata__SetMeasurepointResponsePoint         *message);
size_t setmeasurepointresponsedata__set_measurepoint_response_point__get_packed_size
                     (const Setmeasurepointresponsedata__SetMeasurepointResponsePoint   *message);
size_t setmeasurepointresponsedata__set_measurepoint_response_point__pack
                     (const Setmeasurepointresponsedata__SetMeasurepointResponsePoint   *message,
                      uint8_t             *out);
size_t setmeasurepointresponsedata__set_measurepoint_response_point__pack_to_buffer
                     (const Setmeasurepointresponsedata__SetMeasurepointResponsePoint   *message,
                      ProtobufCBuffer     *buffer);
Setmeasurepointresponsedata__SetMeasurepointResponsePoint *
       setmeasurepointresponsedata__set_measurepoint_response_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   setmeasurepointresponsedata__set_measurepoint_response_point__free_unpacked
                     (Setmeasurepointresponsedata__SetMeasurepointResponsePoint *message,
                      ProtobufCAllocator *allocator);
/* Setmeasurepointresponsedata__SetMeasurepointResponsePoints methods */
void   setmeasurepointresponsedata__set_measurepoint_response_points__init
                     (Setmeasurepointresponsedata__SetMeasurepointResponsePoints         *message);
size_t setmeasurepointresponsedata__set_measurepoint_response_points__get_packed_size
                     (const Setmeasurepointresponsedata__SetMeasurepointResponsePoints   *message);
size_t setmeasurepointresponsedata__set_measurepoint_response_points__pack
                     (const Setmeasurepointresponsedata__SetMeasurepointResponsePoints   *message,
                      uint8_t             *out);
size_t setmeasurepointresponsedata__set_measurepoint_response_points__pack_to_buffer
                     (const Setmeasurepointresponsedata__SetMeasurepointResponsePoints   *message,
                      ProtobufCBuffer     *buffer);
Setmeasurepointresponsedata__SetMeasurepointResponsePoints *
       setmeasurepointresponsedata__set_measurepoint_response_points__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   setmeasurepointresponsedata__set_measurepoint_response_points__free_unpacked
                     (Setmeasurepointresponsedata__SetMeasurepointResponsePoints *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Setmeasurepointresponsedata__SetMeasurepointResponsePoint_Closure)
                 (const Setmeasurepointresponsedata__SetMeasurepointResponsePoint *message,
                  void *closure_data);
typedef void (*Setmeasurepointresponsedata__SetMeasurepointResponsePoints_Closure)
                 (const Setmeasurepointresponsedata__SetMeasurepointResponsePoints *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor setmeasurepointresponsedata__set_measurepoint_response_point__descriptor;
extern const ProtobufCMessageDescriptor setmeasurepointresponsedata__set_measurepoint_response_points__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_setmeasurepointresponsepoint_2eproto__INCLUDED */
